### ISSUE TITLE
Adjustment to Documentation

### ISSUE THREAD

**Issue by tgd15** [radxtools/topology-radiomics#15]
In the documentation, could you please add a note indicating outliers are clipped on a per lesion basis? This would notify users to adjust their code accordingly.

Clipping outliers on a per lesion basis does **not** need to be changed. Based on conversations with the lab, this behavior is ok and is needed for viewing the meshes. 

Please let me know if you need any additional information.

Thank you!

**Comment by satishev** [comment]
@tgd15 submit a pull request with the right info in the README.
