### ISSUE TITLE
Image for Documentation

### ISSUE THREAD

**Issue by tgd15** [radxtools/topology-radiomics#17]
Could you please add the following image to the documentation? It provides a really nice visualization of what curvature features look like.

You can find the image [here](https://www.researchgate.net/figure/Topological-characteristics-of-curvature-indices-Each-descriptor-highlights-different_fig5_307303825).

![Topological-characteristics-of-curvature-indices-Each-descriptor-highlights-different](https://user-images.githubusercontent.com/67032884/101434967-8546cb00-38d9-11eb-8e91-a08826f7883d.png)

**Comment by satishev** [comment]
@tgd15 why not just submit a pull request to the README or upload it to the wiki (and link to the README)?
