### ISSUE TITLE
"pip install topology_radiomics" not working

### ISSUE THREAD

**Issue by rohand24** [radxtools/topology-radiomics#18]
![image](https://user-images.githubusercontent.com/24837088/106330967-061aa700-6239-11eb-9eb8-ca5c38d81830.png)

Operating system - Mac OS
Python- 3.7

**Comment by satishev** [comment]
Tagging @robtoth and @neshdev to help. 
We have some other open issues, whic

**Comment by neshdev** [comment]
@tgd15 - Can you use python 3.8?
The package is only for python3.8 atm.

**Comment by rohand24** [comment]
Thank you. That works.
Would be great if the readme.md could be updated with this information.

**Comment by satishev** [comment]
@rohand24 could you submit a pull request updating the README? Thanks!

**Comment by rohand24** [comment]
Submitted one.
